sean_cooper/2019-10-12/solar_system/config/routes.rb
Rails.application.routes.draw do
  root :to => 'planets#index'
  get '/planets' => 'planets#index'
  get '/planets/new' => 'planets#new'
  post '/planets' => 'planets#create'
  get '/planets/:id' => 'planets#show', :as => 'planet'
  get '/planets/:id/edit' => 'planets#edit', :as => 'planet_edit'
  post '/planets/:id' => 'planets#update'
  delete '/planets/:id' => 'planets#destroy'

  get '/movies' => 'movies#index'
  get '/movies/new' => 'movies#new'
  post '/movies' => 'movies#create'
  get '/movies/:id' => 'movies#show', :as => 'movie'
  get '/movies/:id/edit' => 'movies#edit', :as => 'movie_edit'
  post '/movies/:id' => 'movies#update'
  delete '/movies/:id' => 'movies#destroy'
  get 'movies/search' => 'movies#search'

  get '/mountains' => 'mountains#index'
  get '/mountains/new' => 'mountains#new'
  post '/mountains' => 'mountains#create'
  get '/mountains/:id' => 'mountains#show', :as => 'mountain'
  get '/mountains/:id/edit' => 'mountains#edit', :as => 'mountain_edit'
  post '/mountains/:id' => 'mountains#update'
  delete '/mountains/:id' => 'mountains#destroy'

  get '/oceans' => 'oceans#index'
  get '/oceans/new' => 'oceans#new'
  post '/oceans' => 'oceans#create'
  get '/oceans/:id' => 'oceans#show', :as => 'ocean'
  get '/oceans/:id/edit' => 'oceans#edit', :as => 'ocean_edit'
  post '/oceans/:id' => 'oceans#update'
  delete '/oceans/:id' => 'oceans#destroy'

end

sean_cooper/2019-10-12/solar_system/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sean_cooper/2019-10-12/solar_system/app/models/mountain.rb
class Mountain < ActiveRecord::Base
end

sean_cooper/2019-10-12/solar_system/app/models/movie.rb
class Movie < ActiveRecord::Base

end

sean_cooper/2019-10-12/solar_system/app/models/ocean.rb
class Ocean < ActiveRecord::Base
end

sean_cooper/2019-10-12/solar_system/app/models/planet.rb
# == Schema Information
#
# Table name: planets
#
#  id       :integer          primary key
#  name     :text
#  image    :text
#  orbit    :float
#  diameter :float
#  mass     :float
#  moons    :integer
#

class Planet < ActiveRecord::Base
end

sean_cooper/2019-10-12/solar_system/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token # Only for handwritten forms.
end

sean_cooper/2019-10-12/solar_system/app/controllers/mountains_controller.rb
class MountainsController < ApplicationController

    def index
        @mountains = Mountain.all
    end

    def show
        @mountain = Mountain.find params[:id]
    end

    def new
    end

    def create
        mountain = Mountain.new
        mountain.name = params[:name]
        mountain.image = params[:image]
        mountain.description = params[:description]
        mountain.rating = params[:rating]
        mountain.save
        redirect_to movie_path(mountain.id)
    end
    
    def edit
        @mountain = Mountain.find params[:id]
    end

    def update
        mountain = Mountain.find params[:id]
        mountain.name = params[:name]
        mountain.image = params[:image]
        mountain.description = params[:description]
        mountain.rating = params[:rating]
        mountain.save
        redirect_to mountain_path(mountain.id)
    end
    
    def destroy
        mountain = Mountain.find params[:id]
        mountain.destroy
        redirect_to mountains_path
    end

    def search
        @query = Mountain.where(name: params[:query])
    end

end

sean_cooper/2019-10-12/solar_system/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    def index
        @movies = Movie.all
    end

    def show
        @movie = Movie.find params[:id]
    end

    def new
    end

    def create
        movie = Movie.new
        movie.name = params[:name]
        movie.image = params[:image]
        movie.description = params[:description]
        movie.rating = params[:rating]
        movie.save
        redirect_to movie_path(movie.id)
    end
    
    def edit
        @movie = Movie.find params[:id]
    end

    def update
        movie = Movie.find params[:id]
        movie.name = params[:name]
        movie.image = params[:image]
        movie.description = params[:description]
        movie.rating = params[:rating]
        movie.save
        redirect_to movie_path(movie.id)
    end
    
    def destroy
        movie = Movie.find params[:id]
        movie.destroy
        redirect_to movies_path
    end

    def search
        @query = Movie.where(name: params[:query])
    end

end

sean_cooper/2019-10-12/solar_system/app/controllers/oceans_controller.rb
class OceansController < ApplicationController

    def index
        @oceans = Ocean.all
    end

    def show
        @ocean = Ocean.find params[:id]
    end

    def new
    end

    def create
        ocean = Ocean.new
        ocean.name = params[:name]
        ocean.image = params[:image]
        ocean.description = params[:description]
        ocean.rating = params[:rating]
        ocean.save
        redirect_to ocean_path(ocean.id)
    end
    
    def edit
        @ocean = Ocean.find params[:id]
    end

    def update
        ocean = Ocean.find params[:id]
        ocean.name = params[:name]
        ocean.image = params[:image]
        ocean.description = params[:description]
        ocean.rating = params[:rating]
        ocean.save
        redirect_to ocean_path(ocean.id)
    end
    
    def destroy
        ocean = Ocean.find params[:id]
        ocean.destroy
        redirect_to oceans_path
    end

    def search
        @query = Ocean.where(name: params[:query])
    end

end

sean_cooper/2019-10-12/solar_system/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find params[:id]
  end

  def new
  end

  def create
    planet = Planet.new
    planet.name = params[:name]
    planet.image = params[:image]
    planet.orbit = params[:orbit]
    planet.diameter = params[:diameter]
    planet.mass = params[:mass]
    planet.moons = params[:moons]
    planet.save # INSERT, will set a new ID
    redirect_to planet_path(planet.id)
  end

  def edit
    @planet = Planet.find params[:id]
  end

  def update
    planet = Planet.find params[:id]
    planet.name = params[:name]
    planet.image = params[:image]
    planet.orbit = params[:orbit]
    planet.diameter = params[:diameter]
    planet.mass = params[:mass]
    planet.moons = params[:moons]
    planet.save # UPDATE
    redirect_to planet_path(planet.id)
  end

  def destroy
    planet = Planet.find params[:id]
    planet.destroy # Galactus
    redirect_to planets_path
  end
end

sean_cooper/2019-10-12/solar_system/app/helpers/application_helper.rb
module ApplicationHelper
end

sean_cooper/2019-10-12/solar_system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SolarSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">SOMELOGO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/planets">Planets <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/movies">Movies</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/mountains">Mountains</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/oceans">Oceans</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" href="/movies/search" action="/movies/search" method="get">
            <input class="form-control mr-sm-2" type="search" name="query" placeholder="Doesnt work" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

      <%= yield %>

    </div>
  </body>
</html>

sean_cooper/2019-10-12/solar_system/app/views/mountains/edit.html.erb
<h1>Edit Movie</h1>

<form action="<%= mountain_path(@mountain.id) %>" method="post">
  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Mountain name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control-plaintext" name="name" value="<%= @mountain.name %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Image URL</label>
    <div class="col-sm-10">
      <input type="url" class="form-control" name="image" value="<%= @mountain.image %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="description" value="<%= @mountain.description %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Rating</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="rating" value="<%= @mountain.rating %>">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Confirm Edit</button>
</form>

sean_cooper/2019-10-12/solar_system/app/views/mountains/index.html.erb
<div class="container">
  <div class="row">

  <div class="input-box col-md-12">
    <div class="card text-center">
      <div class="card-body">
        <h1 class="card-title">All Mountains</h1>
        <p class="card-text">this page has mountains</p>
        <a href="/mountains/new" class="btn btn-primary">Add a mountain</a>
      </div>
    </div>
  </div>


  <% @mountains.each do |mountain| %>
    <div class="input-box col-sm-12 col-md-6 col-lg-4">
      <div class="card" style="width: 18rem;">
        <img src=<%= mountain.image %> class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= mountain.name %></h5>
          <p class="card-text"><%= mountain.description %></p>
          <p class="card-text">Rating: <%= mountain.rating %></p>
          <a href="/mountains/<%= mountain.id %>" class="btn btn-primary">Edit</a>
        </div>
      </div>
    </div>
  <% end %>

  </div>
</div>

sean_cooper/2019-10-12/solar_system/app/views/mountains/new.html.erb
<h1>New Mountain</h1>

<form action="<%= mountains_path %>" method="post">
  <label>Name:</label>
  <input type="text" name="name" required>
  <label>Image:</label>
  <input type="url" name="image">
  <label>Description:</label>
  <input type="text" name="description">
  <label>Rating:</label>
  <input type="text" name="rating">

  <button>Create mountain</button>
</form>

sean_cooper/2019-10-12/solar_system/app/views/mountains/show.html.erb
<h1><%= @mountain.name %></h1>

<%= image_tag @mountain.image, :class => 'feature' if @mountain.image.present? %>

<ul>
  <li>Name: <%= @mountain.name %></li>
  <li>Image: <%= @mountain.image %></li>
  <li>Description: <%= @mountain.description %></li>
  <li>Rating: <%= @mountain.rating %></li>
</ul>

<div class="controls">
  <%= link_to 'Edit mountain', mountain_edit_path(@mountain.id) %>
  <%= button_to 'Delete mountain', mountain_path(@mountain.id), :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
</div>

sean_cooper/2019-10-12/solar_system/app/views/movies/edit.html.erb
<h1>Edit Movie</h1>

<form action="<%= movie_path(@movie.id) %>" method="post">
  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Movie name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control-plaintext" name="name" value="<%= @movie.name %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Image URL</label>
    <div class="col-sm-10">
      <input type="url" class="form-control" name="image" value="<%= @movie.image %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="description" value="<%= @movie.description %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Rating</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="rating" value="<%= @movie.rating %>">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Confirm Edit</button>
</form>

sean_cooper/2019-10-12/solar_system/app/views/movies/index.html.erb
<div class="container">
  <div class="row">

  <div class="input-box col-md-12">
    <div class="card text-center">
      <div class="card-body">
        <h1 class="card-title">All Movies</h1>
        <p class="card-text">this page has movies</p>
        <a href="/movies/new" class="btn btn-primary">Add a movie</a>
      </div>
    </div>
  </div>


  <% @movies.each do |movie| %>
    <div class="input-box col-sm-12 col-md-6 col-lg-4">
      <div class="card" style="width: 18rem;">
        <img src=<%= movie.image %> class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= movie.name %></h5>
          <p class="card-text"><%= movie.description %></p>
          <p class="card-text">Rating: <%= movie.rating %></p>
          <a href="/movies/<%= movie.id %>" class="btn btn-primary">Edit</a>
        </div>
      </div>
    </div>
  <% end %>

  </div>
</div>

sean_cooper/2019-10-12/solar_system/app/views/movies/new.html.erb
<h1>New Movie</h1>

<form action="<%= movies_path %>" method="post">
  <label>Name:</label>
  <input type="text" name="name" required>
  <label>Image:</label>
  <input type="url" name="image">
  <label>Description:</label>
  <input type="text" name="description">
  <label>Rating:</label>
  <input type="text" name="rating">

  <button>Create movie</button>
</form>

sean_cooper/2019-10-12/solar_system/app/views/movies/search.html.erb
<div class="container">
  <div class="row">

  <div class="input-box col-md-12">
    <div class="card text-center">
      <div class="card-body">
        <h1 class="card-title">Search results</h1>
        <p class="card-text">this page has movies</p>
        <a href="/movies/new" class="btn btn-primary">Add a movie</a>
      </div>
    </div>
  </div>


  <% @query.each do |movie| %>
    <div class="input-box col-sm-12 col-md-6 col-lg-4">
      <div class="card" style="width: 18rem;">
        <img src=<%= movie.image %> class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= movie.name %></h5>
          <p class="card-text"><%= movie.description %></p>
          <p class="card-text">Rating: <%= movie.rating %></p>
          <a href="/movies/<%= movie.id %>" class="btn btn-primary">Edit</a>
        </div>
      </div>
    </div>
  <% end %>

  </div>
</div>

sean_cooper/2019-10-12/solar_system/app/views/movies/show.html.erb
<h1><%= @movie.name %></h1>

<%= image_tag @movie.image, :class => 'feature' if @movie.image.present? %>

<ul>
  <li>Name: <%= @movie.name %></li>
  <li>Image: <%= @movie.image %></li>
  <li>Description: <%= @movie.description %></li>
  <li>Rating: <%= @movie.rating %></li>
</ul>

<div class="controls">
  <%= link_to 'Edit movie', movie_edit_path(@movie.id) %>
  <%= button_to 'Delete movie', movie_path(@movie.id), :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
</div>

sean_cooper/2019-10-12/solar_system/app/views/oceans/edit.html.erb
<h1>Edit Ocean</h1>

<form action="<%= ocean_path(@ocean.id) %>" method="post">
  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Ocean name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control-plaintext" name="name" value="<%= @ocean.name %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Image URL</label>
    <div class="col-sm-10">
      <input type="url" class="form-control" name="image" value="<%= @ocean.image %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Description</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="description" value="<%= @ocean.description %>">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Rating</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="rating" value="<%= @ocean.rating %>">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Confirm Edit</button>
</form>

sean_cooper/2019-10-12/solar_system/app/views/oceans/index.html.erb
<div class="container">
  <div class="row">

  <div class="input-box col-md-12">
    <div class="card text-center">
      <div class="card-body">
        <h1 class="card-title">All Oceans</h1>
        <p class="card-text">this page has oceans</p>
        <a href="/oceans/new" class="btn btn-primary">Add a ocean</a>
      </div>
    </div>
  </div>


  <% @oceans.each do |ocean| %>
    <div class="input-box col-sm-12 col-md-6 col-lg-4">
      <div class="card" style="width: 18rem;">
        <img src=<%= ocean.image %> class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= ocean.name %></h5>
          <p class="card-text"><%= ocean.description %></p>
          <p class="card-text">Rating: <%= ocean.rating %></p>
          <a href="/oceans/<%= ocean.id %>" class="btn btn-primary">Edit</a>
        </div>
      </div>
    </div>
  <% end %>

  </div>
</div>

sean_cooper/2019-10-12/solar_system/app/views/oceans/new.html.erb
<h1>New Ocean</h1>

<form action="<%= oceans_path %>" method="post">
  <label>Name:</label>
  <input type="text" name="name" required>
  <label>Image:</label>
  <input type="url" name="image">
  <label>Description:</label>
  <input type="text" name="description">
  <label>Rating:</label>
  <input type="text" name="rating">

  <button>Create ocean</button>
</form>

sean_cooper/2019-10-12/solar_system/app/views/oceans/show.html.erb
<h1><%= @ocean.name %></h1>

<%= image_tag @ocean.image, :class => 'feature' if @ocean.image.present? %>

<ul>
  <li>Name: <%= @ocean.name %></li>
  <li>Image: <%= @ocean.image %></li>
  <li>Description: <%= @ocean.description %></li>
  <li>Rating: <%= @ocean.rating %></li>
</ul>

<div class="controls">
  <%= link_to 'Edit ocean', ocean_edit_path(@ocean.id) %>
  <%= button_to 'Delete ocean', ocean_path(@ocean.id), :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
</div>

sean_cooper/2019-10-12/solar_system/app/views/planets/edit.html.erb
<h1>Edit Planet</h1>

<form action="<%= planet_path(@planet.id) %>" method="post">
  <label>Name:</label>
  <input type="text" name="name" value="<%= @planet.name %>" required>
  <label>Image:</label>
  <input type="url" name="image" value="<%= @planet.image %>">
  <label>Orbit:</label>
  <input type="number" name="orbit" value="<%= @planet.orbit %>">
  <label>Diameter:</label>
  <input type="number" name="diameter" value="<%= @planet.diameter %>">
  <label>Mass:</label>
  <input type="number" name="mass" value="<%= @planet.mass %>">
  <label>Moons:</label>
  <input type="number" name="moons" value="<%= @planet.moons %>">

  <button>Update planet</button>
</form>

sean_cooper/2019-10-12/solar_system/app/views/planets/index.html.erb
<div class="card text-center">
  <div class="card-body">
    <h1 class="card-title">All Planets</h1>
    <p class="card-text">Planet time</p>
    <a href="/planets/new" class="btn btn-primary">Add a Planet</a>
  </div>
</div>


<% @planets.each do |planet| %>
  <p>
    <%= link_to planet.name, planet_path(planet.id) %>
    has
    <%= pluralize planet.moons, 'moon' %>.
  </p>
<% end %>

sean_cooper/2019-10-12/solar_system/app/views/planets/new.html.erb
<h1>New Planet</h1>

<form action="<%= planets_path %>" method="post">
  <label>Name:</label>
  <input type="text" name="name" required>
  <label>Image:</label>
  <input type="url" name="image">
  <label>Orbit:</label>
  <input type="number" name="orbit">
  <label>Diameter:</label>
  <input type="number" name="diameter">
  <label>Mass:</label>
  <input type="number" name="mass">
  <label>Moons:</label>
  <input type="number" name="moons">

  <button>Create planet</button>
</form>

sean_cooper/2019-10-12/solar_system/app/views/planets/show.html.erb
<h1><%= @planet.name %></h1>

<%= image_tag @planet.image, :class => 'feature' if @planet.image.present? %>

<ul>
  <li>Name: <%= @planet.name %></li>
  <li>Orbit: <%= @planet.orbit %></li>
  <li>Diameter: <%= @planet.diameter %></li>
  <li>Mass: <%=  @planet.mass %></li>
  <li>Moons: <%= @planet.moons %></li>
</ul>

<div class="controls">
  <%= link_to 'Edit planet', planet_edit_path(@planet.id) %>
  <%= button_to 'Delete planet', planet_path(@planet.id), :method => 'delete', :data => {:confirm => 'Are you sure?'} %>
</div>